"""Standard department report generator using omega_agents + Claude"""
from typing import Dict, Any
from datetime import datetime, timezone
import logging
from app.infrastructure.ai._text_compat import generate_text

logger = logging.getLogger(__name__)


async def _generate_standard_report(
    supabase,
    department: str,
    director: Dict[str, Any],
    sub_agents: list,
    requested_by: str,
) -> Dict[str, Any]:
    """Generate standard department report using omega_agents + Claude analysis"""
    timestamp = datetime.now(timezone.utc).isoformat()

    total_tasks = sum(a.get("tasks_completed_total", 0) for a in sub_agents)
    if director:
        total_tasks += director.get("tasks_completed_total", 0)

    perf_scores = [a.get("performance_score", 0) for a in sub_agents if a.get("performance_score", 0) > 0]
    if director and director.get("performance_score", 0) > 0:
        perf_scores.append(director.get("performance_score", 0))

    avg_performance = round(sum(perf_scores) / len(perf_scores)) if perf_scores else 0
    promotable_count = sum(1 for a in sub_agents if a.get("is_promotable", False))

    _MEMBER_SEPARATOR = "  \n"
    agent_details = []
    if director:
        agent_details.append(
            f"**Director:** {director.get('name')} - {director.get('tasks_completed_total', 0)} tasks"
        )

    for agent in sub_agents:
        status_emoji = "✅" if agent.get("status") == "active" else "⚠️"
        agent_details.append(
            f"{status_emoji} **{agent.get('name')}** - "
            f"{agent.get('tasks_completed_total', 0)} tasks completed"
        )

    prompt = f"""Generate a brief executive summary for the {department} department with these metrics:

- Total agents: {len(sub_agents) + (1 if director else 0)}
- Total tasks completed: {total_tasks}
- Average performance score: {avg_performance}/100
- Promotable agents: {promotable_count}

Focus on: performance trends, team health, and recommendations.
Keep it under 150 words."""

    try:
        ai_summary = await generate_text(
            agent_code="analytics", prompt=prompt, max_tokens=300, temperature=0.7
        )
    except Exception as e:
        logger.warning(f"Claude analysis failed: {e}")
        ai_summary = "Analysis unavailable at this time."

    markdown = f"""# {department.title()} Department Performance Report
**Generated:** {timestamp}
**Requested by:** {requested_by}
**Average Performance:** {avg_performance}/100

---

## Leadership

{agent_details[0] if agent_details else 'No director assigned'}

---

## Team Members

{_MEMBER_SEPARATOR.join(agent_details[1:]) if len(agent_details) > 1 else 'No sub-agents'}

---

## Performance Metrics

- **Total Tasks Completed:** {total_tasks}
- **Average Score:** {avg_performance}/100
- **Promotable Agents:** {promotable_count}
- **Team Size:** {len(sub_agents) + (1 if director else 0)}

---

## AI Analysis

{ai_summary}

---

_Report generated by OMEGA Intelligence System 🐢💎_
"""

    return {
        "success": True,
        "department": department,
        "markdown": markdown,
        "metadata": {
            "timestamp": timestamp,
            "requested_by": requested_by,
            "agent_count": len(sub_agents) + (1 if director else 0),
            "total_tasks": total_tasks,
            "average_score": avg_performance,
            "promotable_count": promotable_count,
        },
    }
