"""Security department report generator: crosses omega_agents with sentinel_scans"""
from typing import Dict, Any
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


async def _generate_security_report(
    supabase, director: Dict[str, Any], sub_agents: list, requested_by: str
) -> Dict[str, Any]:
    """Generate security department report with sentinel_scans data"""
    scans_resp = supabase.client.table("sentinel_scans")\
        .select("*")\
        .order("created_at", desc=True)\
        .limit(50)\
        .execute()

    scans = scans_resp.data or []

    latest_scans = {}
    for scan in scans:
        agent_code = scan.get("agent_code")
        if agent_code and agent_code not in latest_scans:
            latest_scans[agent_code] = scan

    global_score = 100
    try:
        full_resp = supabase.client.table("sentinel_scans")\
            .select("security_score")\
            .eq("scan_type", "full")\
            .order("created_at", desc=True)\
            .limit(1)\
            .execute()
        if full_resp.data:
            global_score = full_resp.data[0].get("security_score", 100)
    except Exception:
        pass

    timestamp = datetime.utcnow().isoformat()

    director_score = 0
    director_status = "unknown"
    if director:
        dir_code = director.get("agent_code", "")
        if dir_code in latest_scans:
            director_score = latest_scans[dir_code].get("security_score", 0)
            director_status = latest_scans[dir_code].get("status", "unknown")
        else:
            director_score = global_score
            director_status = "pass"

    agent_sections = []
    total_score = director_score
    count = 1

    for agent in sub_agents:
        agent_code = agent.get("agent_code", "")
        agent_name = agent.get("name", "Unknown")

        if agent_code in latest_scans:
            scan = latest_scans[agent_code]
            score = scan.get("security_score", 0)
            status = scan.get("status", "unknown")
            last_run = scan.get("created_at", "N/A")
            issues_count = len(scan.get("issues", []))
            total_score += score
            count += 1
            agent_sections.append(f"""
### {agent_name} ({agent_code})
- **Score:** {score}/100
- **Status:** {status}
- **Last Scan:** {last_run}
- **Issues Found:** {issues_count}
- **Tasks Completed:** {agent.get('tasks_completed_total', 0)}
""")
        else:
            total_score += global_score
            count += 1
            agent_sections.append(f"""
### {agent_name} ({agent_code})
- **Score:** {global_score}/100
- **Status:** pass (inherited from global scan)
- **Tasks Completed:** {agent.get('tasks_completed_total', 0)}
""")

    avg_score = round(total_score / count) if count > 0 else 0

    markdown = f"""# Security Department Performance Report
**Generated:** {timestamp}
**Requested by:** {requested_by}
**Average Security Score:** {avg_score}/100

---

## Director

### {director.get('name', 'N/A') if director else 'No Director'}
- **Score:** {director_score}/100
- **Status:** {director_status}
- **Tasks Completed:** {director.get('tasks_completed_total', 0) if director else 0}

---

## Security Agents

{''.join(agent_sections)}

---

## Summary

- **Total Agents:** {len(sub_agents) + (1 if director else 0)}
- **Average Score:** {avg_score}/100
- **Deploy Status:** {'APPROVE' if avg_score >= 70 else 'BLOCK'}

_Report generated by OMEGA Intelligence System 🐢💎_
"""

    return {
        "success": True,
        "department": "security",
        "markdown": markdown,
        "metadata": {
            "timestamp": timestamp,
            "requested_by": requested_by,
            "agent_count": len(sub_agents) + (1 if director else 0),
            "average_score": avg_score,
            "deploy_status": "APPROVE" if avg_score >= 70 else "BLOCK",
        },
    }
