"""seed_prompt_vault.py · Sprint 1 · CONTENT_LAB §5

Seedea los 36 prompts canónicos de RAFA (copywriter) en prompt_vault.
Idempotente: upsert on_conflict=(category, vertical, platform, slot_name).
Verticales: construction, health, real_estate, restaurant, technology.

Requiere: SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY (env vars · G6).
Spec schema: supabase/migrations/00014 + 00015.
"""
import os
import sys

from supabase import create_client


def _env(key: str) -> str:
    v = os.environ.get(key)
    if not v:
        sys.exit(f"❌ Falta env var requerida: {key}")
    return v


PROMPTS = [
    {"category": "script", "vertical": "construction", "platform": "instagram", "performance_score": 9.2, "slot_name": "script", "prompt_text": "Crea script para Reel time-lapse de proyecto completo (30-60s):\n- OPENING (0-5s): Toma del \"before\" con texto overlay \"Día 1\"\n- TIME-LAPSE (6-50s): Secuencia acelerada mostrando progreso día a día\n- REVEAL (51-58s): Resultado final con música de impacto\n- CTA (59-60s): Logo + texto \"¿Tu proyecto? Escríbenos\"\nDatos del cliente: {client_name}, {niche}, {brand_voice}\nTono: {tone}. Audiencia: {target_audience}"},
    {"category": "caption", "vertical": "restaurant", "platform": "instagram", "performance_score": 9.1, "slot_name": "daily_special", "prompt_text": "Crea caption para plato del día/special del restaurante:\n- HOOK VISUAL: Nombre del plato + emoji apetitoso\n- DESCRIPCIÓN SENSORIAL: Describe sabores, texturas, aromas (2-3 líneas)\n- HISTORIA: Origen del plato o qué lo hace especial (1-2 líneas)\n- DISPONIBILIDAD: \"Solo hoy\" o \"Esta semana\"\n- CTA: \"Reserva ahora\" o \"Visítanos hoy\"\n- HASHTAGS: 5-8 relevantes al final\nCliente: {client_name}. Tono: {tone}. Audiencia: {target_audience}"},
    {"category": "caption", "vertical": "real_estate", "platform": "instagram", "performance_score": 9.0, "slot_name": "luxury_storytelling", "prompt_text": "Escribe caption de lujo para propiedad premium usando storytelling:\n- HERO: El comprador ideal (ejecutivo, familia exitosa, inversor)\n- SETTING: Describe la propiedad como escenario de vida ideal\n- TRANSFORMATION: Cómo cambia la vida al vivir ahí\n- PROOF: 1-2 características únicas y verificables\n- CTA: \"Agenda tu visita privada\" + datos de contacto\nMax 220 palabras. Tono: {tone}. Audiencia: {target_audience}"},
    {"category": "script", "vertical": "restaurant", "platform": "instagram", "performance_score": 9.0, "slot_name": "script", "prompt_text": "Crea script para Reel mostrando preparación de plato signature (30s):\n- HOOK (0-3s): Close-up del plato final + texto \"Así hacemos nuestro [plato]\"\n- PREP (4-25s): Secuencia rápida del chef preparando, ingredientes frescos\n- REVEAL (26-28s): Plato completo con cliente satisfecho\n- CTA (29-30s): Nombre del restaurante + \"Reserva ya\"\nEnfatizar: frescura, tradición, amor por la cocina\nCliente: {client_name}. Tono: {tone}"},
    {"category": "caption", "vertical": "health", "platform": "instagram", "performance_score": 8.9, "slot_name": "patient_testimonial", "prompt_text": "Escribe caption compartiendo testimonio de paciente/cliente (con permiso):\n- OPENING: \"Historias como la de [Nombre] nos recuerdan por qué hacemos esto\"\n- SITUATION: Breve contexto del reto que tenía (sin detalles médicos privados)\n- TRANSFORMATION: Resultado específico y mensurable\n- EMOTION: Cómo impactó su vida (trabajo, familia, autoestima)\n- CTA: \"¿Tu historia podría ser la próxima?\"\nTono empático, nunca exagerado. Cliente: {client_name}"},
    {"category": "caption", "vertical": "construction", "platform": "instagram", "performance_score": 8.8, "slot_name": "before_after", "prompt_text": "Crea caption para post Before/After de proyecto de construcción:\n- HOOK: Frase impactante sobre transformación\n- CONTEXT: Breve historia del proyecto (qué era antes, el reto)\n- PROCESS: 1-2 decisiones técnicas que marcaron la diferencia\n- RESULT: Metros cuadrados, tiempo, presupuesto (si el cliente autoriza)\n- CTA: \"¿Tu espacio tiene potencial? Hablemos\"\nTono profesional pero accesible. Cliente: {client_name}"},
    {"category": "script", "vertical": "restaurant", "platform": "tiktok", "performance_score": 8.8, "slot_name": "script", "prompt_text": "Crea script para video estilo \"reacción de cliente\" al probar plato (15-20s):\n- SETUP (0-3s): Cliente sentado, mesero trae el plato\n- FIRST BITE (4-8s): Close-up de la cara + reacción auténtica\n- QUOTE (9-14s): Frase del cliente sobre el plato (guion sugerido)\n- LOGO (15-17s): Nombre del restaurante + dirección\nHook de TikTok: empezar con la reacción, no con la llegada del plato\nCliente: {client_name}. Tono: {tone}"},
    {"category": "script", "vertical": "real_estate", "platform": "instagram", "performance_score": 8.7, "slot_name": "script", "prompt_text": "Crea script para Reel de property tour (15-30 segundos):\n- HOOK (0-3s): Frase impactante + texto on-screen impactante\n- TOUR (4-20s): 4-5 tomas rápidas de las mejores features\n- PRICE/CTA (21-28s): Precio si aplica + \"Link en bio para más info\"\nMostrar: cocina, sala principal, el mejor ángulo exterior\nEvitar: baños principales, closets vacíos, áreas sin terminar\nCliente: {client_name}. Tono: {tone}"},
    {"category": "caption", "vertical": "restaurant", "platform": "instagram", "performance_score": 8.7, "slot_name": "weekend_event", "prompt_text": "Escribe caption para evento especial de fin de semana:\n- HEADLINE: Nombre del evento + fecha con urgencia\n- QUÉ: Breve descripción (música, menú especial, tema)\n- POR QUÉ IR: 2-3 razones específicas que creen FOMO\n- DETALLES: Hora, reservas, precio si aplica\n- CTA: \"Reserva ahora · Solo X mesas disponibles\"\nCrear urgencia real, no inventada. Cliente: {client_name}"},
    {"category": "script", "vertical": "health", "platform": "instagram", "performance_score": 8.6, "slot_name": "script", "prompt_text": "Crea script para Reel de tip rápido de salud (15-30s):\n- HOOK (0-3s): Pregunta o statement provocador\n- TIP (4-20s): Explica el tip visualmente (máximo 1 concepto)\n- RESULTADO (21-26s): Qué mejora al aplicarlo\n- CTA (27-30s): \"Síguenos para más tips\" + nombre del profesional\nLenguaje: simple, nunca técnico. Evitar: diagnosis, garantías\nCliente: {client_name}. Especialidad: {niche}"},
    {"category": "caption", "vertical": "real_estate", "platform": "instagram", "performance_score": 8.5, "slot_name": "aida_framework", "prompt_text": "Crea caption usando framework AIDA:\n- ATTENTION: Hook en 3 palabras máximo\n- INTEREST: 2-3 características únicas que no tienen los competidores\n- DESIRE: Imagina la vida ahí · escena específica del día a día ideal\n- ACTION: CTA específico con baja fricción (\"Escríbenos HOY\")\nMax 200 palabras. 5-8 hashtags al final.\nCliente: {client_name}. Tono: {tone}"},
    {"category": "story", "vertical": "restaurant", "platform": "instagram", "performance_score": 8.5, "slot_name": "story", "prompt_text": "Crea secuencia de 5 Stories para lanzar nuevo menú:\nSTORY 1: Teaser - texto misterioso + countdown sticker\nSTORY 2: Reveal - \"Nuevo Menú Disponible AHORA\" + imagen del menú\nSTORY 3-4: Showcase 2-3 platos estrella con descripción corta\nSTORY 5: CTA - \"¿Cuál probás primero?\" + poll sticker con 2 opciones\nCada story: max 7 palabras de texto visible. Fondo oscuro si posible.\nCliente: {client_name}"},
    {"category": "caption", "vertical": "health", "platform": "instagram", "performance_score": 8.4, "slot_name": "educational_tip", "prompt_text": "Crea caption educativo sobre tip de salud/wellness:\n- HOOK: Dato sorprendente o mito común a romper\n- EDUCACIÓN: Explica el concepto en lenguaje simple (no jerga médica)\n- APLICACIÓN: Cómo el lector puede implementarlo HOY\n- CREDIBILIDAD: Menciona la fuente o tu experiencia brevemente\n- CTA: \"¿Tenías esto claro?\" + invita a comentar\nTono: experto pero accesible. Evitar: exageraciones, garantías\nCliente: {client_name}"},
    {"category": "story", "vertical": "construction", "platform": "instagram", "performance_score": 8.3, "slot_name": "story", "prompt_text": "Crea secuencia de 4 Stories para actualizar progreso de obra:\nSTORY 1: Wide shot del proyecto con texto \"Update: [Nombre Proyecto]\"\nSTORY 2: Close-up de detalle interesante + explicación breve\nSTORY 3: Team en acción (humaniza la empresa)\nSTORY 4: \"¿Cuándo lo terminamos?\" + fecha estimada + CTA\nMostrar progreso real, no solo lo perfecto. Eso genera confianza.\nCliente: {client_name}"},
    {"category": "ad", "vertical": "restaurant", "platform": "facebook", "performance_score": 8.3, "slot_name": "ad", "prompt_text": "Crea Facebook Ad para promoción o inauguración:\n- HEADLINE: Oferta clara y urgente (max 40 chars)\n- HOOK: Por qué es imperdible · experiencia única\n- BODY: Detalles de la oferta + lo que incluye\n- SOCIAL PROOF: \"Más de X personas ya lo probaron\" si aplica\n- CTA button: \"Reservar ahora\" o \"Ver menú\"\nObjetivo: clicks a link o mensaje directo\nCliente: {client_name}. Presupuesto ad: {ad_budget}"},
    {"category": "ad", "vertical": "real_estate", "platform": "facebook", "performance_score": 8.2, "slot_name": "ad", "prompt_text": "Crea Facebook Ad para compradores primerizos usando PAS:\n- PROBLEM: Describe el dolor de rentar sin construir patrimonio\n- AGITATE: Cuánto pierde cada mes que sigue rentando\n- SOLUTION: Tu propiedad como la respuesta concreta\n- PROOF: Precio, ubicación, facilidades de financiamiento\n- CTA: \"Ver propiedades disponibles\"\nTono: empático y empoderador, nunca alarmista\nCliente: {client_name}"},
    {"category": "story", "vertical": "health", "platform": "instagram", "performance_score": 8.1, "slot_name": "story", "prompt_text": "Crea secuencia de Stories para FAQ de salud/wellness:\nSTORY 1: \"Q&A Time\" + Question sticker\nSTORY 2-5: Responde 3-4 preguntas populares de tus pacientes/clientes\nFormato por pregunta: Texto de la pregunta (arriba) · Respuesta corta (abajo)\nSTORY final: \"¿Más preguntas? DM directo o agenda aquí\"\nLas preguntas deben ser reales y frecuentes, no genéricas\nCliente: {client_name}. Especialidad: {niche}"},
    {"category": "ad", "vertical": "construction", "platform": "facebook", "performance_score": 8.1, "slot_name": "ad", "prompt_text": "Crea Facebook Ad para servicios de remodelación usando PAS:\n- PROBLEM: El miedo al desorden, los sobrecostos y el tiempo\n- AGITATE: Lo que cuesta esperar (valor de la propiedad, comodidad)\n- SOLUTION: Cómo tu empresa elimina esos 3 miedos específicamente\n- GUARANTEE: Si ofreces garantía de precio o tiempo, mencionarla\n- CTA: \"Cotización gratis en 24h\"\nCliente: {client_name}"},
    {"category": "story", "vertical": "real_estate", "platform": "instagram", "performance_score": 8.0, "slot_name": "story", "prompt_text": "Crea secuencia de 3 Stories para promover open house:\nSTORY 1 (Teaser): Fachada o mejor feature + fecha y hora + countdown timer\nSTORY 2 (Details): 3 razones para venir · fotos interiores mejores\nSTORY 3 (CTA): \"Confirma tu asistencia\" + link o DM + \"Cupos limitados\"\nUrgencia real, no inventada. Si hay cupos limitados, mencionarlo.\nCliente: {client_name}"},
    {"category": "caption", "vertical": "construction", "platform": "instagram", "performance_score": 7.9, "slot_name": "behind_the_scenes", "prompt_text": "Escribe caption para post Behind-The-Scenes del proceso constructivo:\n- EDUCACIÓN: Explica brevemente qué etapa del proceso se muestra\n- EXPERTISE: Menciona por qué se hace así y qué diferencia hace\n- HUMANIZACIÓN: Nombra al equipo o al maestro de obra si es posible\n- ORGULLO: \"Así se construye en {client_name}\"\n- CTA: Pregunta que invite a comentar sobre el proceso\nTono: experto pero accesible, orgulloso del oficio"},
    {"category": "email", "vertical": "health", "platform": "email", "performance_score": 7.9, "slot_name": "email", "prompt_text": "Escribe email para serie de tips de salud (nurturing):\n- SUBJECT: Curioso y específico (max 50 chars)\n- PERSONAL OPENING: \"Hola [Nombre],\" + referencia a email anterior\n- TIP PRINCIPAL: 1 tip concreto con evidencia breve\n- APLICACIÓN: Cómo implementarlo esta semana\n- BONUS: Recurso gratuito o próximo tip\n- CTA: \"Responde este email con tus dudas\"\nTono cálido, no corporativo. Sin jerga médica.\nCliente: {client_name}"},
    {"category": "email", "vertical": "real_estate", "platform": "email", "performance_score": 7.8, "slot_name": "email", "prompt_text": "Escribe email de seguimiento para lead que visitó propiedad pero no decidió:\n- SUBJECT: Personalizado y curioso (no pushy)\n- OPENING: Agradece la visita + referencia específica a algo que le gustó\n- VALUE ADD: Información nueva que no sabía en la visita\n- OBJECTION HANDLER: Aborda la duda más común sin mencionarla directamente\n- SOFT CTA: \"¿Tienes 10 minutos esta semana para una llamada rápida?\"\nTono: consultor amigo, nunca vendedor presionante\nCliente: {client_name}"},
    {"category": "ad", "vertical": "health", "platform": "facebook", "performance_score": 7.8, "slot_name": "ad", "prompt_text": "Crea Facebook Ad para servicio de wellness usando beneficios:\n- HEADLINE: Beneficio claro y measurable\n- OPENING: Identificar el pain point sin dramatizar\n- SOLUTION: Cómo tu servicio lo resuelve específicamente\n- SOCIAL PROOF: Número de pacientes/clientes o resultado promedio\n- CTA: \"Agenda tu consulta gratuita\"\nCumplir regulaciones de salud: evitar garantías de resultados\nCliente: {client_name}"},
    {"category": "post", "vertical": "construction", "platform": "linkedin", "performance_score": 7.7, "slot_name": "post", "prompt_text": "Escribe post LinkedIn mostrando proyecto como case study:\n- HOOK: Resultado específico en 1 línea\n- CHALLENGE: El desafío que tenía el cliente\n- APPROACH: Las 2-3 decisiones clave que tomamos\n- RESULT: Métricas reales (m², tiempo, presupuesto)\n- LESSON: Qué aprendimos o confirmamos\n- CTA: \"¿Tienes un proyecto similar? Comentá o escríbeme\"\nTono: experto reflexivo, no autopromocional. Max 500 palabras.\nCliente: {client_name}"},
    {"category": "email", "vertical": "restaurant", "platform": "email", "performance_score": 7.7, "slot_name": "email", "prompt_text": "Escribe email de agradecimiento post-visita para fomentar retorno:\n- SUBJECT: \"Gracias por visitarnos, [Nombre]\"\n- APERTURA: Agradecimiento genuino y personalizado\n- PERSONAL TOUCH: Si tienes data, menciona qué pidió o la ocasión\n- VALUE: Razón específica para volver (nuevo plato, evento próximo)\n- REWARD: Descuento o beneficio exclusivo por ser cliente recurrente\n- CTA: \"Reserva tu próxima visita con 10% de descuento\"\nTono cálido y familiar, como si escribiera el dueño directamente\nCliente: {client_name}"},
    {"category": "email", "vertical": "construction", "platform": "email", "performance_score": 7.6, "slot_name": "email", "prompt_text": "Escribe email de seguimiento después de enviar cotización:\n- SUBJECT: \"[Nombre], ¿revisaste la propuesta para tu [proyecto]?\"\n- OPENING: Recap breve de lo que incluye la cotización\n- VALUE REMINDER: El mayor beneficio que ofreces vs competencia\n- URGENCY: Razón legítima para decidir pronto (disponibilidad, precios)\n- FLEXIBILITY: Ofrece ajustar el alcance si el presupuesto es el freno\n- CTA: \"¿Podemos hablar 15 minutos esta semana?\"\nTono: profesional y seguro, nunca desesperado\nCliente: {client_name}"},
    {"category": "post", "vertical": "real_estate", "platform": "linkedin", "performance_score": 7.5, "slot_name": "post", "prompt_text": "Escribe post LinkedIn posicionando al agente como experto del mercado:\n- HOOK: Dato sorprendente o contraintuitivo del mercado local\n- CONTEXTO: Por qué ese dato importa para compradores/inversores\n- ANÁLISIS: Tu perspectiva como experto (no como vendedor)\n- PREDICCIÓN: Qué crees que va a pasar en los próximos 6-12 meses\n- CTA: \"¿Qué opinas? Me interesa tu perspectiva\"\nPosicionamiento: eres el experto, no el vendedor. Max 400 palabras\nCliente: {client_name}"},
    {"category": "post", "vertical": "restaurant", "platform": "google_business", "performance_score": 7.5, "slot_name": "post", "prompt_text": "Escribe post corto para Google My Business:\nTIPOS (alternar según día):\n1. SPECIAL: \"Plato del Día: [Nombre] - [Precio]. Solo hoy. Reserva: [teléfono]\"\n2. EVENTO: \"[Evento] este [día] · [Hora] · Reserva requerida: [contacto]\"\n3. TIP: \"¿Sabías que [dato sobre el restaurante]?\"\nMax 300 palabras. Sin hashtags. Siempre incluir horario o teléfono.\nCliente: {client_name}. Horario: {business_hours}"},
    {"category": "post", "vertical": "health", "platform": "linkedin", "performance_score": 7.4, "slot_name": "post", "prompt_text": "Escribe post LinkedIn posicionando al profesional de salud como autoridad:\n- HOOK: Tendencia actual en salud que observas en tu práctica\n- PERSPECTIVA EXPERTA: Tu análisis profesional (cita literatura si aplica)\n- CASO REAL: Ejemplo anonimizado que ilustra el punto\n- IMPLICACIÓN: Qué deberían hacer los lectores con esta información\n- CTA: \"¿Cuántos de ustedes han visto esto en sus pacientes?\"\nTono: colega a colega, no maestro a alumno. Max 350 palabras\nCliente: {client_name}. Especialidad: {niche}"},
    {"category": "hashtags", "vertical": "real_estate", "platform": "instagram", "performance_score": 7.2, "slot_name": "hashtags", "prompt_text": "Genera set estratégico de 25-30 hashtags para post de real estate:\nCATEGORÍAS A INCLUIR:\n- Brand/Location (5-7): Ciudad + tipo de propiedad + nombre de agencia\n- Property Type (5-7): #CasaEnVenta #Apartamento etc según propiedad\n- Lifestyle (5-7): El estilo de vida que representa la propiedad\n- Trending Local (3-5): Hashtags de trending local de la ciudad/país\n- Niche (3-4): Hashtags específicos del tipo de cliente objetivo\nMezclar tamaños: 30% grandes (1M+) · 50% medianos (100K-1M) · 20% pequeños (<100K)\nCiudad: {region}. Tipo: {property_type}"},
    {"category": "caption", "vertical": "technology", "platform": "instagram", "performance_score": 8.9, "slot_name": "product_launch", "prompt_text": "Escribe caption para anuncio de lanzamiento de producto/feature SaaS:\n- HOOK: Frase corta sobre el problema concreto que el producto resuelve\n- DESCRIPCIÓN: Qué hace la herramienta + 2-3 beneficios medibles (no features técnicos)\n- SOCIAL PROOF: Resultado de beta/piloto o métrica de early adopters (si aplica)\n- CTA: \"Empieza gratis hoy · link en bio\" o \"Reserva tu demo\"\n- HASHTAGS: 5-7 mezclando tech + nicho del cliente\nSin jerga innecesaria. Cliente: {client_name}. Tono: {tone}. Audiencia: {target_audience}"},
    {"category": "caption", "vertical": "technology", "platform": "instagram", "performance_score": 8.7, "slot_name": "feature_announcement", "prompt_text": "Crea caption para anuncio de nueva feature en producto existente:\n- HOOK VISUAL: \"Nuevo en {client_name}: [feature]\" con emoji de impacto\n- ANTES/AHORA: Cómo era el workflow antes vs cómo es ahora (2 líneas máx cada uno)\n- CASO DE USO: 1 ejemplo concreto y específico de quién la usa y para qué\n- CTA: \"Disponible ya · entra a tu cuenta\" o \"Prueba la nueva versión\"\n- HASHTAGS: 5-6 relevantes al nicho\nTono: {tone}. Cliente: {client_name}. Audiencia: {target_audience}"},
    {"category": "caption", "vertical": "technology", "platform": "linkedin", "performance_score": 8.8, "slot_name": "b2b_case_study", "prompt_text": "Escribe post LinkedIn estilo case-study B2B (max 280 palabras):\n- HOOK: Cliente + métrica concreta de impacto (ej \"Cómo X redujo Y un Z%\")\n- CONTEXTO: Industria del cliente + reto que enfrentaba (2-3 líneas)\n- SOLUCIÓN: Qué implementaron con {client_name} (sin overselling, factual)\n- RESULTADO: 2-3 métricas verificables (tiempo, $, % mejora)\n- QUOTE: 1 cita textual del cliente (real, con permiso)\n- CTA: \"¿Tu equipo enfrenta algo similar? Hablemos\"\nSin buzzwords vacíos. Cliente: {client_name}. Audiencia: {target_audience}"},
    {"category": "script", "vertical": "technology", "platform": "instagram", "performance_score": 8.6, "slot_name": "product_demo_reel", "prompt_text": "Crea script para Reel de demo de producto SaaS (20-30s):\n- HOOK (0-3s): Pantalla con el problema/dolor del usuario + texto overlay punzante\n- DEMO (4-22s): 3-4 clicks máx mostrando la solución en acción (screen recording)\n- PROOF (23-27s): Métrica/resultado overlay (tiempo ahorrado, etc)\n- CTA (28-30s): Logo {client_name} + \"Link en bio · Empieza gratis\"\nVelocidad: rápida pero legible · texto siempre en pantalla por sordos/mudo\nCliente: {client_name}. Tono: {tone}. Audiencia: {target_audience}"},
    {"category": "caption", "vertical": "technology", "platform": "instagram", "performance_score": 8.4, "slot_name": "build_in_public", "prompt_text": "Escribe caption tipo \"building in public\" para mostrar proceso de desarrollo:\n- HOOK: Algo que aprendiste/decidiste/cambiaste esta semana en el producto\n- CONTEXTO: Qué problema interno motivó esa decisión (sin spoilers competitivos)\n- DECISIÓN: Qué hiciste y por qué (técnico pero accesible)\n- LEARNING: 1 insight aplicable para otros founders/dev teams\n- CTA: \"¿Cómo lo resolverías tú? Comentá\" o \"Seguinos para más\"\nTono honesto, no autopromocional. Cliente: {client_name}. Brand voice: {brand_voice}"},
    {"category": "caption", "vertical": "technology", "platform": "facebook", "performance_score": 8.5, "slot_name": "saas_pricing_offer", "prompt_text": "Crea caption Facebook para oferta/promoción de plan SaaS:\n- HOOK: Valor concreto del plan en una línea (qué resuelve, para quién)\n- DESCRIPCIÓN: 3-4 features clave del plan promocionado (bullets cortos)\n- DIFERENCIADOR: 1 razón por la que este plan vs alternativas\n- URGENCIA: Plazo o cupos reales (sin inventar escasez)\n- CTA: \"Activa tu plan · link abajo\" con URL clara\n- DISCLAIMER: \"Aplican términos · ver detalles en sitio\" si corresponde\nTono: {tone}. Cliente: {client_name}. Audiencia: {target_audience}"},
]


def main() -> None:
    url, key = _env("SUPABASE_URL"), _env("SUPABASE_SERVICE_ROLE_KEY")
    client = create_client(url, key)
    rows = [{**p, "agent_code": "RAFA", "version": 1, "is_active": True} for p in PROMPTS]
    client.table("prompt_vault").upsert(rows, on_conflict="category,vertical,platform,slot_name").execute()
    res = client.table("prompt_vault").select("id", count="exact").execute()
    n = res.count or 0
    print(f"OK · {n} prompts en vault" if n == 36 else f"FAIL · esperaba 36, encontre {n}")
    sys.exit(0 if n == 36 else 1)


if __name__ == "__main__":
    main()
